
DROP TABLE USER;
--유저 테이블

CREATE TABLE "USER"(
	USER_ID VARCHAR2(30) NOT NULL,
	USER_NAME VARCHAR2(30) NOT NULL,
	USER_PW VARCHAR2(40) NOT NULL,
	USER_GENDER VARCHAR2(10) NOT NULL,
	USER_NICKNAME VARCHAR2(30) NOT NULL,
	USER_EMAIL VARCHAR2(30) NOT NULL,
	USER_HP VARCHAR2(30) NOT NULL,
	USER_PHOTO VARCHAR2(100),
	USER_AGE NUMBER(3) NOT NULL,
	USER_ADMIN NUMBER(2) DEFAULT 0,
	CONSTRAINT USER_PK PRIMARY KEY (USER_ID,USER_NICKNAME),	
	CONSTRAINT USER_NAME_CK CHECK(NOT REGEXP_LIKE(USER_NAME,'[[:punct:]]|[[:digit:]]')), 
	CONSTRAINT USER_NICKNAME_CK CHECK(NOT REGEXP_LIKE(USER_NICKNAME,'[[:punct:]]')), 
	CONSTRAINT USER_ID_CK CHECK(REGEXP_LIKE(USER_ID,'[A-Za-z0-9]')), 
	CONSTRAINT USER_HP_CK CHECK(LENGTH(USER_HP) = 11 AND REGEXP_LIKE(USER_HP,'^[0-9]*$')), 
	CONSTRAINT USER_EMAIL_CK CHECK(USER_EMAIL LIKE '%@%')
);


SELECT * FROM USER;


INSERT INTO HR.USER
(USER_ID, USER_NAME, USER_PW, USER_GENDER, USER_NICKNAME, USER_EMAIL, USER_HP, USER_PHOTO, USER_AGE, USER_ADMIN)
VALUES('hys02544', '하야시', 'Fytergk908!@#', '남', '하야시', 'df@nadf.com', '01000000000', 'none', 23, 0);

